# Submodules keep their inputs and outputs inline in their own README.md.
formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - inputs
    - outputs

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  description: true
  escape: true
  hide-empty: true
  required: true
  sensitive: true
  type: true
