name: tf-checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/basic/'
      provider: none

  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/complete/'
      provider: none

  dns_records:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/dns-records/'
      provider: none

  ssl_for_saas:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/ssl-for-saas/'
      provider: none
